server:
  port: 9090
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/aftas
    username: mizo
    password: changemeinprod!
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
