version: "3.9"
services:
  spring-app:
    container_name: aftas-app
    build:
      context: ./AFTAS_Backend
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/aftas
      - SPRING_DATASOURCE_USERNAME=mizo
      - SPRING_DATASOURCE_PASSWORD=changemeinprod!
    networks:
      - aftas
    depends_on:
      - postgres-db
  postgres-db:
    container_name: aftas-postgres
    image: "postgres"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "mizo"
      POSTGRES_PASSWORD: "changemeinprod!"
      POSTGRES_DB: "aftas"
    volumes:
      - postgres-db:/var/lib/postgresql/data
    networks:
      - aftas
  lma7al-front:
    container_name: lma7al-front
    build:
      context: ./Lma7al-front
      dockerfile: Dockerfile.prod
    ports:
      - "4200:4200"
    expose:
      - "4200"
    environment:
      - MOD=dev
    volumes:
      - ./Lma7al-front:/app/lma7al-front
      - /app/lma7al-front/node_modules
    depends_on:
      - spring-app
    networks:
      - aftas

networks:
  aftas:
    driver: bridge

volumes:
  postgres-db:
    driver: local