server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/aftas
    username: postgres
    password: aymane@123
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

jwt:
  secret: 100aa60b3972fe7bc2aa2f7358d7b6d052e86e9bafa85c9fa335e203b7281846
