server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hibernate
    username: aymane
    password: aymane@123
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update